name: Biodiversity Farms
favicon: null
layout_spectrum: 0.42120916163548827
typography_spectrum: 0.5736789046786726
title: We farm rare and endangered spieces to provide the pharmaceutical and life science laboratories the best molecules available in nature
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3757744338363409
  lightness: 0.16363443294540048
  saturation: 0.17189637245610356
  rhythmicContrast: 0.22639051219448447
purpose: []
